#!/usr/bin/env python3
"""Generate a Flyway migration that loads the question bank.

    python3 scripts/generate_bank_migration.py --version 11

Reads content/bank/*.json and writes
backend/src/main/resources/db/migration/V<version>__load_question_bank.sql.

The migration is insert-only, per specs/how-to-seed-the-question-bank.md: it creates the bank's
topics, inserts every question, and inserts every option with the misconception code it was
written to catch. It never updates or deletes a question or an option, so it cannot overwrite a
question a teacher has since edited. For the same reason it is a one-shot artefact: to add or
change content once it has been applied, use the admin screens, not a regenerated V<version>.

Two traps it avoids, both of which have taken production down or nearly so:

  * no row id is ever named. Topics are looked up by slug and question ids are left to SQLite.
  * options are attached through a captured id (a one-row temp table), not through
    last_insert_rowid() inside the option INSERT - that value moves as each option is inserted -
    and not by matching on the prompt, which silently attaches to the first match if two questions
    share one.

Run content/render.py --check first: this script trusts the bank's shape, and render.py is what
checks it.
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BANK_DIR = os.path.join(ROOT, "content", "bank")
MIGRATION_DIR = os.path.join(ROOT, "backend", "src", "main", "resources", "db", "migration")

LABELS = "ABCDEF"

# The prototype topics, with the names V2 gave them. `fractions` is the one slug the new bank
# shares, and the row is repurposed rather than duplicated; the guard on the old name means a
# teacher who has renamed it keeps their name.
PROTOTYPE_NAMES = {
    "number": "Number & Place Value",
    "fractions": "Fractions, Decimals & Percentages",
    "algebra": "Algebra",
    "geometry": "Geometry & Measures",
    "data": "Probability & Statistics",
}


def text(value: str) -> str:
    """A SQL string literal. Content contains apostrophes, semicolons and non-ASCII maths."""
    return "'" + value.replace("'", "''") + "'"


def nullable(value):
    return "null" if value is None else text(value)


def load_topics():
    topics = []
    for path in sorted(glob.glob(os.path.join(BANK_DIR, "*.json"))):
        with open(path, encoding="utf-8") as handle:
            topics.append(json.load(handle))
    return topics


def header(version, topics):
    questions = sum(len(topic["questions"]) for topic in topics)
    options = sum(len(q["options"]) for topic in topics for q in topic["questions"])
    wrong = sum(1 for topic in topics for q in topic["questions"] for o in q["options"] if not o["correct"])
    return f"""-- The Year 7/8 Number & Algebra question bank: {questions} questions across {len(topics)} topics.
--
-- Generated by `python3 scripts/generate_bank_migration.py --version {version}` from
-- content/bank/*.json, and checked by `python3 content/render.py --check`. Do not edit it by hand:
-- edit the JSON and generate the next migration.
--
-- Insert-only. Nothing here updates or deletes a question, an option or a topic's questions, so
-- applying it can never overwrite a question a teacher has edited. It runs after the retire
-- migration that immediately precedes it, which clears the previous bank out of the way; running
-- the sweep after this migration would retire this bank too.
--
-- Every wrong option carries the misconception code it was written to catch, in
-- answer_options.misconception_code (V9). There are {wrong} of them. The register that defines the
-- codes is content/misconceptions.json; the codes are stored so a wrong answer can be read as a
-- named error rather than only as a wrong number.
--
-- Inserted as origin = 'SEED': this is the bank the app ships with, as opposed to content a
-- teacher writes ('AUTHORED') or imports ('IMPORTED').

-- Topics. `fractions` already exists - it held the prototype's combined Fractions, Decimals &
-- Percentages topic - so it is repurposed for this bank's Fractions topic, keeping its slug and id
-- so any recorded session still resolves. Its old name is replaced only if nobody has changed it.
insert into topics (slug, name, description, sort_order) values
"""


def topic_rows(topics):
    rows = []
    for order, topic in enumerate(topics, start=1):
        rows.append(
            "    ({}, {}, {}, {})".format(
                text(topic["slug"]), text(topic["name"]), nullable(topic.get("description")), order
            )
        )
    return ",\n".join(rows) + "\non conflict(slug) do nothing;\n"


def repurpose_fractions(topics):
    for order, topic in enumerate(topics, start=1):
        if topic["slug"] in PROTOTYPE_NAMES:
            old = PROTOTYPE_NAMES[topic["slug"]].replace("'", "''")
            return (
                "\n-- The prototype row, repurposed. Guarded on the old name so a teacher's rename is\n"
                "-- not overwritten.\n"
                "update topics set name = {}, description = {}, sort_order = {}\n"
                " where slug = {} and name = '{}';\n".format(
                    text(topic["name"]),
                    nullable(topic.get("description")),
                    order,
                    text(topic["slug"]),
                    old,
                )
            )
    return ""


def question_block(topic, question):
    answer_type = question["answerType"]
    options = question["options"]
    assert answer_type in ("SINGLE_CHOICE", "MULTI_SELECT"), question["key"]
    correct = sum(1 for option in options if option["correct"])
    assert correct == 1 if answer_type == "SINGLE_CHOICE" else correct >= 1, question["key"]
    assert 2 <= len(options) <= 6, question["key"]

    lines = [
        f"\n-- {question['key']}  (band {question['band']}, {answer_type.lower()})",
        "insert into questions (topic_id, prompt, explanation, difficulty, status, origin, answer_type, year_group)",
        "values ((select id from topics where slug = {}), {}, {}, {}, 'PUBLISHED', 'SEED', {}, {});".format(
            text(topic["slug"]),
            text(question["prompt"]),
            nullable(question.get("explanation")),
            question["band"],
            text(answer_type),
            topic["yearGroup"],
        ),
        "delete from seed_question;",
        "insert into seed_question (id) select last_insert_rowid();",
        "insert into answer_options (question_id, position, label, text, is_correct, misconception_code) values",
    ]
    rows = []
    for index, option in enumerate(options):
        code = None if option["correct"] else option.get("catches")
        assert option["correct"] or code, question["key"]
        rows.append(
            "    ((select id from seed_question), {}, '{}', {}, {}, {})".format(
                index + 1, LABELS[index], text(option["text"]), 1 if option["correct"] else 0, nullable(code)
            )
        )
    lines.append(",\n".join(rows) + ";")
    return "\n".join(lines)


def feedback_migration(version, topics):
    """The messages a student reads, as a migration of their own.

    The bank was loaded by V11 before options carried a message, and an applied migration is frozen:
    its checksum is recorded and it cannot be edited. So the column and the messages arrive together
    here, and a fresh database reaches the same state as a deployed one by the same route.
    """
    questions = sum(len(topic["questions"]) for topic in topics)
    updates = []
    for topic in topics:
        for question in topic["questions"]:
            for index, option in enumerate(question["options"]):
                if option["correct"]:
                    continue
                # A wrong option needs a message; render.py enforces the same rule.
                assert option.get("feedback"), question["key"]
                updates.append(
                    "update answer_options set feedback = {}\n"
                    " where position = {}\n"
                    "   and question_id = (select id from questions where prompt = {} and origin = 'SEED');".format(
                        text(option["feedback"]), index + 1, text(question["prompt"])
                    )
                )
    return (
        f"""-- The message a student reads when they pick this wrong option: {len(updates)} of them.
--
-- Generated by `python3 scripts/generate_bank_migration.py --feedback --version {version}` from
-- content/bank/*.json, and checked by `python3 content/render.py --check`.
--
-- A migration of its own rather than part of the load (V11), because V11 had already been applied
-- when messages were added and an applied migration is frozen - its checksum is recorded, so
-- editing it fails validation on the next start. Adding the column and filling it here means a
-- fresh database reaches the same state as a deployed one by the same route.
--
-- The message belongs to the option, not to the misconception code. One code can cover two options
-- in a question that are different misreadings: in "What is the value of the 2 in 5.320?", 0.2 means
-- the student read the 2 as tenths and 0.002 means they read it as thousandths, and both catch
-- PV-COLUMN-NAME. So the sentence that says "on the question you think you were asked, 0.2 is the
-- right answer" has to hang on the option. Across the {questions} questions there are {len(updates)}
-- wrong options, and each one has its own message.
--
-- Nullable, because a correct option has nothing to explain away, and an option a teacher writes may
-- carry only a misconception code - in which case the register's line for that code stands in.

alter table answer_options add column feedback varchar(500);

"""
        + "\n".join(updates)
        + "\n"
    )


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", type=int, required=True, help="Flyway version number, e.g. 12")
    parser.add_argument(
        "--feedback",
        action="store_true",
        help="emit the migration that adds answer_options.feedback and fills it, instead of the load",
    )
    parser.add_argument("--dry-run", action="store_true", help="print the migration instead of writing it")
    args = parser.parse_args()

    topics = load_topics()
    if not topics:
        print("no topic files found in content/bank", file=sys.stderr)
        return 1

    if args.feedback:
        sql = feedback_migration(args.version, topics)
        if args.dry_run:
            print(sql)
            return 0
        out = os.path.join(MIGRATION_DIR, f"V{args.version}__answer_option_feedback.sql")
        with open(out, "w", encoding="utf-8") as handle:
            handle.write(sql)
        updates = sql.count("update answer_options")
        print(f"wrote {os.path.relpath(out, ROOT)}")
        print(f"  {updates} messages, {len(sql.splitlines())} lines")
        return 0

    chunks = [header(args.version, topics), topic_rows(topics), repurpose_fractions(topics)]
    chunks.append(
        "\n-- The id of the question just inserted, one row at a time. Cleared before each capture, so\n"
        "-- the subquery below can only ever match one row. `if not exists` so that a later load\n"
        "-- migration in the same Flyway run, which reuses the connection, does not collide with this\n"
        "-- one's temp table.\n"
        "create temp table if not exists seed_question (id integer);\n"
    )
    for topic in topics:
        for question in topic["questions"]:
            chunks.append(question_block(topic, question))

    sql = "".join(chunks)
    if args.dry_run:
        print(sql)
        return 0

    os.makedirs(MIGRATION_DIR, exist_ok=True)
    out = os.path.join(MIGRATION_DIR, f"V{args.version}__load_question_bank.sql")
    with open(out, "w", encoding="utf-8") as handle:
        handle.write(sql)

    questions = sum(len(topic["questions"]) for topic in topics)
    options = sum(len(q["options"]) for topic in topics for q in topic["questions"])
    print(f"wrote {os.path.relpath(out, ROOT)}")
    print(f"  {questions} questions, {options} options, {len(sql.splitlines())} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
